version: 0.1
phases:
    install:
        commands:
            - npm install -g @angular/cli
    build:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - echo Build started on `date`
            - ng build --env=${BUILD_ENV}
    post_build:
         commands:
            - aws s3 cp dist s3://${S3_BUCKET} --recursive
            - aws configure set preview.cloudfront true
            - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths '/*'
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
